application: craigsreptile
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /tasks/.*
  script: handlers/tasks.py
  login: admin
- url: /services/.*
  script: handlers/services.py
- url: .*
  script: handlers/main.py

builtins:
- datastore_admin: on
